import { chromium } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const baseURL=process.env.TEST_BASE_URL||'http://localhost:8888';
const browser=await chromium.launch({channel:'msedge',headless:true});
const context=await browser.newContext({baseURL});
await context.addInitScript(()=>{window.shareMode='unsupported';window.shareCalls=[];Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>window.shareMode!=='unsupported'});Object.defineProperty(navigator,'share',{configurable:true,value:async data=>{window.shareCalls.push({name:data.files[0].name,type:data.files[0].type,size:data.files[0].size,text:data.text,isFile:data.files[0] instanceof File});if(window.shareMode==='cancel')throw new DOMException('Cancelled','AbortError');if(window.shareMode==='error')throw new DOMException('Unavailable','NotAllowedError');}});});
const page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));const results=[];const pass=name=>{results.push(name);console.log(`PASS ${name}`);};
await mkdir('artifacts',{recursive:true});
try{
await page.goto(baseURL);await page.locator('#access').waitFor();
assert.equal((await page.request.get('/api/scope-config')).status(),401);assert.equal((await page.request.get('/netlify/functions/lib/catalog.mjs')).status(),404);pass('private catalogue and sources protected');
await page.locator('#access-code').fill('wrong');await page.locator('#unlock-button').click();await page.getByText('The access code is incorrect. Please try again.').waitFor();
await page.locator('#access-code').fill('local-test-code');await page.locator('#unlock-button').click();await page.locator('#proposal').waitFor({state:'visible'});pass('real authentication and incorrect-code handling');
const sectionOrder=['Website Foundation','Core Operational Features','Ongoing Website Care & Improvement','Optional Advancements','Quotation Summary'];
assert.deepEqual(await page.locator('.scope-content > section h2').allTextContents(),sectionOrder);
assert.equal(await page.locator('#care-details .care-inclusions li').count(),12);
assert.ok((await page.locator('#care-details').innerText()).includes('28,000/month'));
assert.ok((await page.locator('#care-details').innerText()).includes('Billing begins 30 days after launch.'));
assert.ok((await page.locator('#care-details').innerText()).includes('Domain registration and renewal charges are payable by Zadok Farm at their actual cost.'));
assert.ok((await page.locator('#desktop-summary .total-block').innerText()).includes('112,000'));
pass('five-section pricing order and recurring care terms without changing foundation fee');

await page.locator('#select-payments').check();for(const id of ['catalogue','basket','records','staff'])assert.equal(await page.locator(`#select-${id}`).isChecked(),true);pass('automatic transitive dependencies');
await page.locator('#select-catalogue').click();await page.locator('#cancel-change').click();assert.equal(await page.locator('#select-payments').isChecked(),true);await page.locator('#select-catalogue').click();await page.locator('#confirm-change').click();assert.equal(await page.locator('#select-payments').isChecked(),false);pass('dependency removal cancellation and confirmation');
await page.locator('#select-training').check();await page.locator('#select-accounting').check();await page.reload();await page.locator('#proposal').waitFor({state:'visible'});assert.equal(await page.locator('#select-training').isChecked(),true);pass('draft restoration');
for(const width of [360,390,768,1024,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#ongoing-care').screenshot({path:`artifacts/care-${width}.png`});pass(`editing layout ${width}px without overflow`);}
await page.route('**/api/quotation',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'SERVER_ERROR',message:'Validation temporarily unavailable.'}})}));
await page.locator('.summary-panel .review-button').click();await page.getByText('Validation temporarily unavailable.').waitFor();assert.equal(await page.locator('#main').getAttribute('data-state'),'editing');pass('validation failure preserves editable scope');await page.unroute('**/api/quotation');
let validations=0;page.on('request',req=>{if(new URL(req.url()).pathname==='/api/quotation')validations++;});
await page.route('**/api/quotation-pdf',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'PDF_ERROR',message:'PDF temporarily unavailable.'}})}));
await page.locator('.summary-panel .review-button').click();await page.locator('#quotation-review').waitFor({state:'visible'});await page.getByText('PDF temporarily unavailable.').waitFor();assert.equal(await page.locator('#share-quote').isDisabled(),true);pass('single review action and recoverable PDF failure');await page.unroute('**/api/quotation-pdf');
await page.locator('#retry-pdf').click();await page.waitForFunction(()=>document.querySelector('#main').dataset.state==='generating_pdf');assert.equal(await page.locator('#share-quote').isDisabled(),true);await page.waitForFunction(()=>!document.querySelector('#share-quote').disabled);assert.equal(validations,1);pass('generation loading prevents repeat actions without another validation');
assert.ok((await page.locator('#review-content').innerText()).includes('Automatically included for:'));assert.ok((await page.locator('#review-content').innerText()).includes('Optional modules not selected'));pass('review includes descriptions, dependencies and exclusions');
assert.deepEqual(await page.locator('#review-content h2').allTextContents(),sectionOrder);
assert.ok((await page.locator('#review-content .care-section').innerText()).includes('scoped and approved separately before work begins.'));
assert.ok((await page.locator('#review-content .total-block').innerText()).includes('252,000'));
assert.ok(!(await page.locator('#review-content .total-block').innerText()).includes('28,000'));
assert.ok((await page.locator('#review-content .recurring-summary').innerText()).includes('28,000/month'));
pass('review separates one-time fee and monthly care in the required order');
for(const width of [360,390,768,1024,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`artifacts/review-${width}.png`,fullPage:true});}pass('review responsive at all five widths');
await page.locator('#preview-pdf').click();await page.locator('#preview-dialog').waitFor({state:'visible'});assert.ok((await page.locator('#pdf-preview').getAttribute('src')).startsWith('blob:'));await page.keyboard.press('Escape');assert.equal(await page.locator('#preview-pdf').evaluate(el=>el===document.activeElement),true);pass('PDF preview, Escape and focus restoration');
let downloadEvent=page.waitForEvent('download');await page.locator('#quotation-review .download-pdf').click();let download=await downloadEvent;assert.match(download.suggestedFilename(),/^Zadok-Farm-Project-Scope-ZF-\d{8}-[A-F0-9]{16}\.pdf$/);await download.saveAs('artifacts/generated-quotation.pdf');pass('separate Download PDF with exact filename');
downloadEvent=page.waitForEvent('download');await page.locator('#share-quote').click();await downloadEvent;await page.locator('#quotation-share').waitFor({state:'visible'});assert.equal(await page.locator('#main').getAttribute('data-state'),'share_opened');assert.equal(await page.locator('#share-message').innerText(),'Your quotation has been downloaded. Open WhatsApp and attach the downloaded PDF to complete the process.');const message=new URL(await page.locator('#open-whatsapp').getAttribute('href')).searchParams.get('text');assert.ok(message.startsWith('Good evening Alfred. I\u2019ve reviewed'));assert.ok(!message.includes('285,000'));pass('unsupported file-share downloads PDF and offers short WhatsApp handoff');
await page.locator('#return-quote').click();await page.evaluate(()=>window.shareMode='supported');await page.locator('#share-quote').click();await page.locator('#quotation-share').waitFor({state:'visible'});let calls=await page.evaluate(()=>window.shareCalls);assert.equal(calls.length,1);assert.ok(calls[0].isFile);assert.equal(calls[0].type,'application/pdf');assert.equal(calls[0].text,message);assert.ok(calls[0].size>1000);assert.equal(await page.locator('#share-message').innerText(),'Your device\u2019s share options have been opened. Select WhatsApp and send the attached quotation to complete the process.');pass('simulated native share receives PDF File and exact short message');
await page.locator('#return-quote').click();await page.evaluate(()=>window.shareMode='cancel');await page.locator('#share-quote').click();await page.getByText('Sharing was cancelled. Your quotation is still ready to download or share.').waitFor();assert.equal(await page.locator('#main').getAttribute('data-state'),'review_ready');pass('native cancellation returns to quotation without delivery claim');
await page.evaluate(()=>window.shareMode='error');await page.locator('#share-quote').click();await page.locator('#manual-fallback').waitFor({state:'visible'});pass('native sharing error offers manual fallback');
await page.locator('#back-edit').click();await page.locator('#proposal').waitFor({state:'visible'});assert.equal(await page.locator('#main').getAttribute('data-state'),'editing');assert.equal(await page.locator('#select-training').isChecked(),true);pass('back to edit keeps selections and invalidates prepared PDF');
assert.deepEqual(errors,[]);pass('no browser runtime errors');await writeFile('artifacts/browser-results.json',JSON.stringify({checks:results.length,results,errors},null,2));
}finally{await browser.close();}
